name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # optional: build on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pulumi-node-aws:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pulumi-node-aws:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pulumi-node-aws:${{ github.ref_name }}
